/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.booking.bank;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class TransactionEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 365508461657006621L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TransactionEvent\",\"namespace\":\"com.booking.bank\",\"fields\":[{\"name\":\"txId\",\"type\":\"int\"},{\"name\":\"txType\",\"type\":\"string\"},{\"name\":\"amount\",\"type\":\"double\"},{\"name\":\"timestamp\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<TransactionEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<TransactionEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<TransactionEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<TransactionEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<TransactionEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this TransactionEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a TransactionEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a TransactionEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static TransactionEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private int txId;
  private java.lang.CharSequence txType;
  private double amount;
  private java.time.Instant timestamp;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public TransactionEvent() {}

  /**
   * All-args constructor.
   * @param txId The new value for txId
   * @param txType The new value for txType
   * @param amount The new value for amount
   * @param timestamp The new value for timestamp
   */
  public TransactionEvent(java.lang.Integer txId, java.lang.CharSequence txType, java.lang.Double amount, java.time.Instant timestamp) {
    this.txId = txId;
    this.txType = txType;
    this.amount = amount;
    this.timestamp = timestamp.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return txId;
    case 1: return txType;
    case 2: return amount;
    case 3: return timestamp;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null,
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: txId = (java.lang.Integer)value$; break;
    case 1: txType = (java.lang.CharSequence)value$; break;
    case 2: amount = (java.lang.Double)value$; break;
    case 3: timestamp = (java.time.Instant)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'txId' field.
   * @return The value of the 'txId' field.
   */
  public int getTxId() {
    return txId;
  }


  /**
   * Sets the value of the 'txId' field.
   * @param value the value to set.
   */
  public void setTxId(int value) {
    this.txId = value;
  }

  /**
   * Gets the value of the 'txType' field.
   * @return The value of the 'txType' field.
   */
  public java.lang.CharSequence getTxType() {
    return txType;
  }


  /**
   * Sets the value of the 'txType' field.
   * @param value the value to set.
   */
  public void setTxType(java.lang.CharSequence value) {
    this.txType = value;
  }

  /**
   * Gets the value of the 'amount' field.
   * @return The value of the 'amount' field.
   */
  public double getAmount() {
    return amount;
  }


  /**
   * Sets the value of the 'amount' field.
   * @param value the value to set.
   */
  public void setAmount(double value) {
    this.amount = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return The value of the 'timestamp' field.
   */
  public java.time.Instant getTimestamp() {
    return timestamp;
  }


  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(java.time.Instant value) {
    this.timestamp = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Creates a new TransactionEvent RecordBuilder.
   * @return A new TransactionEvent RecordBuilder
   */
  public static com.booking.bank.TransactionEvent.Builder newBuilder() {
    return new com.booking.bank.TransactionEvent.Builder();
  }

  /**
   * Creates a new TransactionEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TransactionEvent RecordBuilder
   */
  public static com.booking.bank.TransactionEvent.Builder newBuilder(com.booking.bank.TransactionEvent.Builder other) {
    if (other == null) {
      return new com.booking.bank.TransactionEvent.Builder();
    } else {
      return new com.booking.bank.TransactionEvent.Builder(other);
    }
  }

  /**
   * Creates a new TransactionEvent RecordBuilder by copying an existing TransactionEvent instance.
   * @param other The existing instance to copy.
   * @return A new TransactionEvent RecordBuilder
   */
  public static com.booking.bank.TransactionEvent.Builder newBuilder(com.booking.bank.TransactionEvent other) {
    if (other == null) {
      return new com.booking.bank.TransactionEvent.Builder();
    } else {
      return new com.booking.bank.TransactionEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for TransactionEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TransactionEvent>
    implements org.apache.avro.data.RecordBuilder<TransactionEvent> {

    private int txId;
    private java.lang.CharSequence txType;
    private double amount;
    private java.time.Instant timestamp;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.booking.bank.TransactionEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.txId)) {
        this.txId = data().deepCopy(fields()[0].schema(), other.txId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.txType)) {
        this.txType = data().deepCopy(fields()[1].schema(), other.txType);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.amount)) {
        this.amount = data().deepCopy(fields()[2].schema(), other.amount);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[3].schema(), other.timestamp);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing TransactionEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.booking.bank.TransactionEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.txId)) {
        this.txId = data().deepCopy(fields()[0].schema(), other.txId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.txType)) {
        this.txType = data().deepCopy(fields()[1].schema(), other.txType);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.amount)) {
        this.amount = data().deepCopy(fields()[2].schema(), other.amount);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[3].schema(), other.timestamp);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'txId' field.
      * @return The value.
      */
    public int getTxId() {
      return txId;
    }


    /**
      * Sets the value of the 'txId' field.
      * @param value The value of 'txId'.
      * @return This builder.
      */
    public com.booking.bank.TransactionEvent.Builder setTxId(int value) {
      validate(fields()[0], value);
      this.txId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'txId' field has been set.
      * @return True if the 'txId' field has been set, false otherwise.
      */
    public boolean hasTxId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'txId' field.
      * @return This builder.
      */
    public com.booking.bank.TransactionEvent.Builder clearTxId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'txType' field.
      * @return The value.
      */
    public java.lang.CharSequence getTxType() {
      return txType;
    }


    /**
      * Sets the value of the 'txType' field.
      * @param value The value of 'txType'.
      * @return This builder.
      */
    public com.booking.bank.TransactionEvent.Builder setTxType(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.txType = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'txType' field has been set.
      * @return True if the 'txType' field has been set, false otherwise.
      */
    public boolean hasTxType() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'txType' field.
      * @return This builder.
      */
    public com.booking.bank.TransactionEvent.Builder clearTxType() {
      txType = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'amount' field.
      * @return The value.
      */
    public double getAmount() {
      return amount;
    }


    /**
      * Sets the value of the 'amount' field.
      * @param value The value of 'amount'.
      * @return This builder.
      */
    public com.booking.bank.TransactionEvent.Builder setAmount(double value) {
      validate(fields()[2], value);
      this.amount = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'amount' field has been set.
      * @return True if the 'amount' field has been set, false otherwise.
      */
    public boolean hasAmount() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'amount' field.
      * @return This builder.
      */
    public com.booking.bank.TransactionEvent.Builder clearAmount() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * @return The value.
      */
    public java.time.Instant getTimestamp() {
      return timestamp;
    }


    /**
      * Sets the value of the 'timestamp' field.
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public com.booking.bank.TransactionEvent.Builder setTimestamp(java.time.Instant value) {
      validate(fields()[3], value);
      this.timestamp = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * @return This builder.
      */
    public com.booking.bank.TransactionEvent.Builder clearTimestamp() {
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public TransactionEvent build() {
      try {
        TransactionEvent record = new TransactionEvent();
        record.txId = fieldSetFlags()[0] ? this.txId : (java.lang.Integer) defaultValue(fields()[0]);
        record.txType = fieldSetFlags()[1] ? this.txType : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.amount = fieldSetFlags()[2] ? this.amount : (java.lang.Double) defaultValue(fields()[2]);
        record.timestamp = fieldSetFlags()[3] ? this.timestamp : (java.time.Instant) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<TransactionEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<TransactionEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<TransactionEvent>
    READER$ = (org.apache.avro.io.DatumReader<TransactionEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










