server:
  port: ${APP_PORT:1234}
  address: 0.0.0.0

spring:
  application:
    name: kafka-avro-springboot
  kafka:
    bootstrap-servers: ${KAFKA_BROKER_HOST:localhost}:9092
    properties:
      schema.registry.url: http://${SCHEMA_REGISTRY_HOST:localhost}:${SCHEMA_REGISTRY_PORT:8081}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    consumer:
      group-id: bank-transactions-consumer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        specific.avro.reader: true
management:
  endpoints:
    web:
      exposure:
        include: "*"   # expose prometheus endpoint
  endpoint:
    prometheus:
      enabled: true
  metrics:
    # optional: add a global tag so all metrics have the application tag
    tags:
      application: banking-kafka-app